name: Unit testing
on: [push]
jobs:
  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "17", "lts/*"]
    name: Testing on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node }}"
          cache: "yarn"
      - run: node --version
      - run: yarn
      - run: yarn test
